name: Build & Publish Docker Image

on:
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize, ready_for_review ]
    paths:
      - 'docker/**' 
      - '.github/workflows/deploy-image.yml'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-3
  ECR_REPO: zama-shop                
  BUILD_CONTEXT: .
  DOCKERFILE: ./docker/Dockerfile

jobs:
  pr-build:
    if: ${{ github.event_name == 'pull_request' && !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0, submodules: recursive }

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ACC_ROLE }}

      - name: Login to ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repo
        run: |
          aws ecr describe-repositories --repository-names "${{ env.ECR_REPO }}" >/dev/null 2>&1 \
            || aws ecr create-repository --repository-name "${{ env.ECR_REPO }}" >/dev/null 2>&1 \
            || aws ecr describe-repositories --repository-names "${{ env.ECR_REPO }}" >/dev/null

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & Push (PR tag)
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPO }}:dev-${{ github.event.pull_request.number }}-${{ github.sha }}
            ${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false