name: Terraform ECR (plan/apply)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      mode:
        description: Terraform action
        type: choice
        options: [plan, apply]
        default: plan
      environment:
        description: GitHub Environment (approvals/secrets)
        type: choice
        options: [dev, prod]
        default: dev

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-3                        # Paris (matches your backend)
  TF_VERSION: 1.8.7
  TF_WORKING_DIR: ./terraform/infra


concurrency:
  group: tf-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'dev' }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify caller identity
        run: aws sts get-caller-identity

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform init (S3 backend)
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform init

      - name: Terraform fmt & validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: |
          terraform fmt -check -recursive
          terraform validate

      - name: Terraform plan
        if: ${{ github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && inputs.mode == 'plan') }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -input=false -no-color

      - name: Terraform apply
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.mode == 'apply' }}
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform apply -input=false -auto-approve