name: Terraform Plan (OIDC test)

on:
  workflow_dispatch: {}
  pull_request:
    branches: [ main ]
    paths:
        - 'terraform/oidc/**' 

permissions:
  id-token: write    # required for GitHub OIDC
  contents: read

env:
  AWS_REGION: eu-west-3
  TF_VERSION: 1.8.7
  TF_WORKING_DIR: ./terraform/oidc


jobs:
  plan:
    runs-on: ubuntu-latest
    environment: dev  

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ACC_ROLE }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify caller identity
        run: aws sts get-caller-identity